# 端口号
server:
  port: 8003

spring:
  application:
    name: service-vod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://服务器地址:3306/edu?serverTimezone=GMT%2B8
    username: #数据库名
    password: #数据库密码
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: Hikari
      max-lifetime: 55000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

aliyun:
  vod:
    file:
      keyid: #自己阿里云keyid
      keysecret: #自己阿里云keysecret
      regionid: #阿里云regionid: 比如cn-shanghai


mybatis-plus:
  mapper-locations: com/example/aclservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl