# 端口号
server:
  port: 8001

spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.73.193:3306/edu?serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: Hikari
      max-lifetime: 55000
#  #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
#  spring.datasource.hikari.minimum-idle=5
#  #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
#  spring.datasource.hikari.maximum-pool-size=15
#  #自动提交从池中返回的连接，默认值为true
#  spring.datasource.hikari.auto-commit=true
#  #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
#  #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
#  spring.datasource.hikari.idle-timeout=30000
#  #连接池名称，默认HikariPool-1
#  spring.datasource.hikari.pool-name=Hikari
#  #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短；单位ms
#  spring.datasource.hikari.max-lifetime=55000
#  #连接超时时间:毫秒，小于250毫秒，会被重置为默认值30秒
#  spring.datasource.hikari.connection-timeout=30000
#  #连接测试查询
#  spring.datasource.hikari.connection-test-query=SELECT 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    host: 43.139.73.193
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: -1

  cloud:
    nacos:
      discovery:
        server-addr: 43.139.73.193:8848

mybatis-plus:
  mapper-locations: com/example/eduservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true