# 端口号
server:
  port: 8009

spring:
  application:
    name: service-oss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.73.193:3306/edu?serverTimezone=GMT%2B8
    username: root
    password: 123456

aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: LTAI5t8wX9VSQCT3NdjFyWEq
      keysecret: 2I9vO7LkZ44731hOnzQ0z8elW1Vr1A
      bucketname: edu-2022-11-20